package libtrace

var (
	type_int          = int(0)
	type_int8         = int8(0)
	type_int16        = int16(0)
	type_int32        = int32(0)
	type_int64        = int64(0)
	type_uint8        = uint8(0)
	type_uint16       = uint16(0)
	type_uint32       = uint32(0)
	type_uint64       = uint64(0)
	type_uintptr      = uintptr(0)
	type_float32      = float32(0)
	type_float64      = float64(0)
	type_stringc      = StringC("")
	type_stringbuffer = StringBuffer("")
	type_buffer       = []byte{}

	type_unknownstruct = struct{}{}
)

var syscalls = []*Signature{

	&Signature{Id: 0, Name: "read", Args: []Arg{Arg{Name: "fd", Type: type_uint32, Const: false}, Arg{Name: "buf", Type: type_stringc, Const: false}, Arg{Name: "count", Type: type_uint64, Const: false}}},
	&Signature{Id: 1, Name: "write", Args: []Arg{Arg{Name: "fd", Type: type_uint32, Const: false}, Arg{Name: "buf", Type: type_stringc, Const: true}, Arg{Name: "count", Type: type_uint64, Const: false}}},
	&Signature{Id: 2, Name: "open", Args: []Arg{Arg{Name: "filename", Type: type_stringc, Const: true}, Arg{Name: "flags", Type: type_int, Const: false}, Arg{Name: "mode", Type: type_int, Const: false}}},
	&Signature{Id: 3, Name: "close", Args: []Arg{Arg{Name: "fd", Type: type_uint32, Const: false}}},
	&Signature{Id: 4, Name: "stat", Args: []Arg{Arg{Name: "filename", Type: type_stringc, Const: true}, Arg{Name: "statbuf", Type: &type_unknownstruct, Const: false}}},
	&Signature{Id: 5, Name: "fstat", Args: []Arg{Arg{Name: "fd", Type: type_uint32, Const: false}, Arg{Name: "statbuf", Type: &type_unknownstruct, Const: false}}},
	&Signature{Id: 6, Name: "lstat", Args: []Arg{Arg{Name: "filename", Type: type_stringc, Const: true}, Arg{Name: "statbuf", Type: &type_unknownstruct, Const: false}}},
	&Signature{Id: 7, Name: "poll", Args: []Arg{Arg{Name: "ufds", Type: &type_unknownstruct, Const: false}, Arg{Name: "nfds", Type: type_uint32, Const: false}, Arg{Name: "timeout_msecs", Type: type_int32, Const: false}}},
	&Signature{Id: 8, Name: "lseek", Args: []Arg{Arg{Name: "fd", Type: type_uint32, Const: false}, Arg{Name: "offset", Type: type_uint32, Const: false}, Arg{Name: "origin", Type: type_uint32, Const: false}}},
	&Signature{Id: 9, Name: "mmap", Args: []Arg{Arg{Name: "addr", Type: type_uint64, Const: false}, Arg{Name: "len", Type: type_uint64, Const: false}, Arg{Name: "prot", Type: type_uint64, Const: false}, Arg{Name: "flags", Type: type_uint64, Const: false}, Arg{Name: "fd", Type: type_uint64, Const: false}, Arg{Name: "off", Type: type_uint64, Const: false}}},
	&Signature{Id: 10, Name: "mprotect", Args: []Arg{Arg{Name: "start", Type: type_uint64, Const: false}, Arg{Name: "len", Type: type_uint64, Const: false}, Arg{Name: "prot", Type: type_uint64, Const: false}}},
	&Signature{Id: 11, Name: "munmap", Args: []Arg{Arg{Name: "addr", Type: type_uint64, Const: false}, Arg{Name: "len", Type: type_uint64, Const: false}}},
	&Signature{Id: 12, Name: "brk", Args: []Arg{Arg{Name: "brk", Type: type_uint64, Const: false}}},
	&Signature{Id: 13, Name: "rt_sigaction", Args: []Arg{Arg{Name: "sig", Type: type_int, Const: false}, Arg{Name: "act", Type: &type_unknownstruct, Const: true}, Arg{Name: "oact", Type: &type_unknownstruct, Const: false}, Arg{Name: "sigsetsize", Type: type_uint64, Const: false}}},
	&Signature{Id: 14, Name: "rt_sigprocmask", Args: []Arg{Arg{Name: "how", Type: type_int, Const: false}, Arg{Name: "nset", Type: &type_unknownstruct, Const: false}, Arg{Name: "oset", Type: &type_unknownstruct, Const: false}, Arg{Name: "sigsetsize", Type: type_uint64, Const: false}}},
	&Signature{Id: 15, Name: "rt_sigreturn", Args: []Arg{Arg{Name: "__unused", Type: type_uint64, Const: false}}},
	&Signature{Id: 16, Name: "ioctl", Args: []Arg{Arg{Name: "fd", Type: type_uint32, Const: false}, Arg{Name: "cmd", Type: type_uint32, Const: false}, Arg{Name: "arg", Type: type_uint64, Const: false}}},
	&Signature{Id: 17, Name: "pread64", Args: []Arg{Arg{Name: "fd", Type: type_uint64, Const: false}, Arg{Name: "buf", Type: type_stringc, Const: false}, Arg{Name: "count", Type: type_uint64, Const: false}, Arg{Name: "pos", Type: type_uint64, Const: false}}},
	&Signature{Id: 18, Name: "pwrite64", Args: []Arg{Arg{Name: "fd", Type: type_uint32, Const: false}, Arg{Name: "buf", Type: type_stringc, Const: true}, Arg{Name: "count", Type: type_uint64, Const: false}, Arg{Name: "pos", Type: type_uint64, Const: false}}},
	&Signature{Id: 19, Name: "readv", Args: []Arg{Arg{Name: "fd", Type: type_uint64, Const: false}, Arg{Name: "vec", Type: &type_unknownstruct, Const: true}, Arg{Name: "vlen", Type: type_uint64, Const: false}}},
	&Signature{Id: 20, Name: "writev", Args: []Arg{Arg{Name: "fd", Type: type_uint64, Const: false}, Arg{Name: "vec", Type: &type_unknownstruct, Const: true}, Arg{Name: "vlen", Type: type_uint64, Const: false}}},
	&Signature{Id: 21, Name: "access", Args: []Arg{Arg{Name: "filename", Type: type_stringc, Const: true}, Arg{Name: "mode", Type: type_int, Const: false}}},
	&Signature{Id: 22, Name: "pipe", Args: []Arg{Arg{Name: "filedes", Type: &type_int, Const: false}}},
	&Signature{Id: 23, Name: "select", Args: []Arg{Arg{Name: "n", Type: type_int, Const: false}, Arg{Name: "inp", Type: &type_unknownstruct, Const: false}, Arg{Name: "outp", Type: &type_unknownstruct, Const: false}, Arg{Name: "exp", Type: &type_unknownstruct, Const: false}, Arg{Name: "tvp", Type: &type_unknownstruct, Const: false}}},
	&Signature{Id: 24, Name: "sched_yield", Args: []Arg{}},
	&Signature{Id: 25, Name: "mremap", Args: []Arg{Arg{Name: "addr", Type: type_uint64, Const: false}, Arg{Name: "old_len", Type: type_uint64, Const: false}, Arg{Name: "new_len", Type: type_uint64, Const: false}, Arg{Name: "flags", Type: type_uint64, Const: false}, Arg{Name: "new_addr", Type: type_uint64, Const: false}}},
	&Signature{Id: 26, Name: "msync", Args: []Arg{Arg{Name: "start", Type: type_uint64, Const: false}, Arg{Name: "len", Type: type_uint64, Const: false}, Arg{Name: "flags", Type: type_int, Const: false}}},
	&Signature{Id: 27, Name: "mincore", Args: []Arg{Arg{Name: "start", Type: type_uint64, Const: false}, Arg{Name: "len", Type: type_uint64, Const: false}, Arg{Name: "vec", Type: type_buffer, Const: false}}},
	&Signature{Id: 28, Name: "madvise", Args: []Arg{Arg{Name: "start", Type: type_uint64, Const: false}, Arg{Name: "len_in", Type: type_uint64, Const: false}, Arg{Name: "behavior", Type: type_int, Const: false}}},
	&Signature{Id: 29, Name: "shmget", Args: []Arg{Arg{Name: "key", Type: type_int32, Const: false}, Arg{Name: "size", Type: type_uint64, Const: false}, Arg{Name: "shmflg", Type: type_int, Const: false}}},
	&Signature{Id: 30, Name: "shmat", Args: []Arg{Arg{Name: "shmid", Type: type_int, Const: false}, Arg{Name: "shmaddr", Type: type_stringc, Const: false}, Arg{Name: "shmflg", Type: type_int, Const: false}}},
	&Signature{Id: 31, Name: "shmctl", Args: []Arg{Arg{Name: "shmid", Type: type_int, Const: false}, Arg{Name: "cmd", Type: type_int, Const: false}, Arg{Name: "buf", Type: &type_unknownstruct, Const: false}}},
	&Signature{Id: 32, Name: "dup", Args: []Arg{Arg{Name: "fildes", Type: type_uint32, Const: false}}},
	&Signature{Id: 33, Name: "dup2", Args: []Arg{Arg{Name: "oldfd", Type: type_uint32, Const: false}, Arg{Name: "newfd", Type: type_uint32, Const: false}}},
	&Signature{Id: 34, Name: "pause", Args: []Arg{}},
	&Signature{Id: 35, Name: "nanosleep", Args: []Arg{Arg{Name: "rqtp", Type: &type_unknownstruct, Const: false}, Arg{Name: "rmtp", Type: &type_unknownstruct, Const: false}}},
	&Signature{Id: 36, Name: "getitimer", Args: []Arg{Arg{Name: "which", Type: type_int, Const: false}, Arg{Name: "value", Type: &type_unknownstruct, Const: false}}},
	&Signature{Id: 37, Name: "alarm", Args: []Arg{Arg{Name: "seconds", Type: type_uint32, Const: false}}},
	&Signature{Id: 38, Name: "setitimer", Args: []Arg{Arg{Name: "which", Type: type_int, Const: false}, Arg{Name: "value", Type: &type_unknownstruct, Const: false}, Arg{Name: "ovalue", Type: &type_unknownstruct, Const: false}}},
	&Signature{Id: 39, Name: "getpid", Args: []Arg{}},
	&Signature{Id: 40, Name: "sendfile", Args: []Arg{Arg{Name: "out_fd", Type: type_int, Const: false}, Arg{Name: "in_fd", Type: type_int, Const: false}, Arg{Name: "offset", Type: &type_uint32, Const: false}, Arg{Name: "count", Type: type_uint64, Const: false}}},
	&Signature{Id: 41, Name: "socket", Args: []Arg{Arg{Name: "family", Type: type_int, Const: false}, Arg{Name: "type", Type: type_int, Const: false}, Arg{Name: "protocol", Type: type_int, Const: false}}},
	&Signature{Id: 42, Name: "connect", Args: []Arg{Arg{Name: "fd", Type: type_int, Const: false}, Arg{Name: "uservaddr", Type: &type_unknownstruct, Const: false}, Arg{Name: "addrlen", Type: type_int, Const: false}}},
	&Signature{Id: 43, Name: "accept", Args: []Arg{Arg{Name: "fd", Type: type_int, Const: false}, Arg{Name: "upeer_sockaddr", Type: &type_unknownstruct, Const: false}, Arg{Name: "upeer_addrlen", Type: &type_int, Const: false}}},
	&Signature{Id: 44, Name: "sendto", Args: []Arg{Arg{Name: "fd", Type: type_int, Const: false}, Arg{Name: "buff", Type: &type_uint8, Const: false}, Arg{Name: "len", Type: type_uint64, Const: false}, Arg{Name: "flags", Type: type_uint32, Const: false}, Arg{Name: "addr", Type: &type_unknownstruct, Const: false}, Arg{Name: "addr_len", Type: type_int, Const: false}}},
	&Signature{Id: 45, Name: "recvfrom", Args: []Arg{Arg{Name: "fd", Type: type_int, Const: false}, Arg{Name: "ubuf", Type: &type_uint8, Const: false}, Arg{Name: "size", Type: type_uint64, Const: false}, Arg{Name: "flags", Type: type_uint32, Const: false}, Arg{Name: "addr", Type: &type_unknownstruct, Const: false}, Arg{Name: "addr_len", Type: &type_int, Const: false}}},
	&Signature{Id: 46, Name: "sendmsg", Args: []Arg{Arg{Name: "fd", Type: type_int, Const: false}, Arg{Name: "msg", Type: &type_unknownstruct, Const: false}, Arg{Name: "flags", Type: type_uint32, Const: false}}},
	&Signature{Id: 47, Name: "recvmsg", Args: []Arg{Arg{Name: "fd", Type: type_int, Const: false}, Arg{Name: "msg", Type: &type_unknownstruct, Const: false}, Arg{Name: "flags", Type: type_uint32, Const: false}}},
	&Signature{Id: 48, Name: "shutdown", Args: []Arg{Arg{Name: "fd", Type: type_int, Const: false}, Arg{Name: "how", Type: type_int, Const: false}}},
	&Signature{Id: 49, Name: "bind", Args: []Arg{Arg{Name: "fd", Type: type_int, Const: false}, Arg{Name: "umyaddr", Type: &type_unknownstruct, Const: false}, Arg{Name: "addrlen", Type: type_int, Const: false}}},
	&Signature{Id: 50, Name: "listen", Args: []Arg{Arg{Name: "fd", Type: type_int, Const: false}, Arg{Name: "backlog", Type: type_int, Const: false}}},
	&Signature{Id: 51, Name: "getsockname", Args: []Arg{Arg{Name: "fd", Type: type_int, Const: false}, Arg{Name: "usockaddr", Type: &type_unknownstruct, Const: false}, Arg{Name: "usockaddr_len", Type: &type_int, Const: false}}},
	&Signature{Id: 52, Name: "getpeername", Args: []Arg{Arg{Name: "fd", Type: type_int, Const: false}, Arg{Name: "usockaddr", Type: &type_unknownstruct, Const: false}, Arg{Name: "usockaddr_len", Type: &type_int, Const: false}}},
	&Signature{Id: 53, Name: "socketpair", Args: []Arg{Arg{Name: "family", Type: type_int, Const: false}, Arg{Name: "type", Type: type_int, Const: false}, Arg{Name: "protocol", Type: type_int, Const: false}, Arg{Name: "usockvec", Type: &type_int, Const: false}}},
	&Signature{Id: 54, Name: "setsockopt", Args: []Arg{Arg{Name: "fd", Type: type_int, Const: false}, Arg{Name: "level", Type: type_int, Const: false}, Arg{Name: "optname", Type: type_int, Const: false}, Arg{Name: "optval", Type: type_stringc, Const: false}, Arg{Name: "optlen", Type: type_int, Const: false}}},
	&Signature{Id: 55, Name: "getsockopt", Args: []Arg{Arg{Name: "fd", Type: type_int, Const: false}, Arg{Name: "level", Type: type_int, Const: false}, Arg{Name: "optname", Type: type_int, Const: false}, Arg{Name: "optval", Type: type_stringc, Const: false}, Arg{Name: "optlen", Type: &type_int, Const: false}}},
	&Signature{Id: 56, Name: "clone", Args: []Arg{Arg{Name: "clone_flags", Type: type_uint64, Const: false}, Arg{Name: "newsp", Type: type_uint64, Const: false}, Arg{Name: "parent_tid", Type: &type_uint8, Const: false}, Arg{Name: "child_tid", Type: &type_uint8, Const: false}}},
	&Signature{Id: 57, Name: "fork", Args: []Arg{}},
	&Signature{Id: 58, Name: "vfork", Args: []Arg{}},
	&Signature{Id: 59, Name: "execve", Args: []Arg{Arg{Name: "filename", Type: type_stringc, Const: true}, Arg{Name: "const argv[]", Type: type_stringc, Const: true}, Arg{Name: "const envp[]", Type: type_stringc, Const: true}}},
	&Signature{Id: 60, Name: "exit", Args: []Arg{Arg{Name: "error_code", Type: type_int, Const: false}}},
	&Signature{Id: 61, Name: "wait4", Args: []Arg{Arg{Name: "upid", Type: type_int32, Const: false}, Arg{Name: "stat_addr", Type: &type_int, Const: false}, Arg{Name: "options", Type: type_int, Const: false}, Arg{Name: "ru", Type: &type_unknownstruct, Const: false}}},
	&Signature{Id: 62, Name: "kill", Args: []Arg{Arg{Name: "pid", Type: type_int32, Const: false}, Arg{Name: "sig", Type: type_int, Const: false}}},
	&Signature{Id: 63, Name: "uname", Args: []Arg{Arg{Name: "name", Type: &type_unknownstruct, Const: false}}},
	&Signature{Id: 64, Name: "semget", Args: []Arg{Arg{Name: "key", Type: type_int32, Const: false}, Arg{Name: "nsems", Type: type_int, Const: false}, Arg{Name: "semflg", Type: type_int, Const: false}}},
	&Signature{Id: 65, Name: "semop", Args: []Arg{Arg{Name: "semid", Type: type_int, Const: false}, Arg{Name: "tsops", Type: &type_unknownstruct, Const: false}, Arg{Name: "nsops", Type: type_uint32, Const: false}}},
	&Signature{Id: 66, Name: "semctl", Args: []Arg{Arg{Name: "semid", Type: type_int, Const: false}, Arg{Name: "semnum", Type: type_int, Const: false}, Arg{Name: "cmd", Type: type_int, Const: false}, Arg{Name: "arg", Type: type_unknownstruct, Const: false}}},
	&Signature{Id: 67, Name: "shmdt", Args: []Arg{Arg{Name: "shmaddr", Type: type_stringc, Const: false}}},
	&Signature{Id: 68, Name: "msgget", Args: []Arg{Arg{Name: "key", Type: type_int32, Const: false}, Arg{Name: "msgflg", Type: type_int, Const: false}}},
	&Signature{Id: 69, Name: "msgsnd", Args: []Arg{Arg{Name: "msqid", Type: type_int, Const: false}, Arg{Name: "msgp", Type: &type_unknownstruct, Const: false}, Arg{Name: "msgsz", Type: type_uint64, Const: false}, Arg{Name: "msgflg", Type: type_int, Const: false}}},
	&Signature{Id: 70, Name: "msgrcv", Args: []Arg{Arg{Name: "msqid", Type: type_int, Const: false}, Arg{Name: "msgp", Type: &type_unknownstruct, Const: false}, Arg{Name: "msgsz", Type: type_uint64, Const: false}, Arg{Name: "msgtyp", Type: type_int32, Const: false}, Arg{Name: "msgflg", Type: type_int, Const: false}}},
	&Signature{Id: 71, Name: "msgctl", Args: []Arg{Arg{Name: "msqid", Type: type_int, Const: false}, Arg{Name: "cmd", Type: type_int, Const: false}, Arg{Name: "buf", Type: &type_unknownstruct, Const: false}}},
	&Signature{Id: 72, Name: "fcntl", Args: []Arg{Arg{Name: "fd", Type: type_uint32, Const: false}, Arg{Name: "cmd", Type: type_uint32, Const: false}, Arg{Name: "arg", Type: type_uint64, Const: false}}},
	&Signature{Id: 73, Name: "flock", Args: []Arg{Arg{Name: "fd", Type: type_uint32, Const: false}, Arg{Name: "cmd", Type: type_uint32, Const: false}}},
	&Signature{Id: 74, Name: "fsync", Args: []Arg{Arg{Name: "fd", Type: type_uint32, Const: false}}},
	&Signature{Id: 75, Name: "fdatasync", Args: []Arg{Arg{Name: "fd", Type: type_uint32, Const: false}}},
	&Signature{Id: 76, Name: "truncate", Args: []Arg{Arg{Name: "path", Type: type_stringc, Const: true}, Arg{Name: "length", Type: type_int32, Const: false}}},
	&Signature{Id: 77, Name: "ftruncate", Args: []Arg{Arg{Name: "fd", Type: type_uint32, Const: false}, Arg{Name: "length", Type: type_uint64, Const: false}}},
	&Signature{Id: 78, Name: "getdents", Args: []Arg{Arg{Name: "fd", Type: type_uint32, Const: false}, Arg{Name: "dirent", Type: &type_unknownstruct, Const: false}, Arg{Name: "count", Type: type_uint32, Const: false}}},
	&Signature{Id: 79, Name: "getcwd", Args: []Arg{Arg{Name: "buf", Type: type_stringc, Const: false}, Arg{Name: "size", Type: type_uint64, Const: false}}},
	&Signature{Id: 80, Name: "chdir", Args: []Arg{Arg{Name: "filename", Type: type_stringc, Const: true}}},
	&Signature{Id: 81, Name: "fchdir", Args: []Arg{Arg{Name: "fd", Type: type_uint32, Const: false}}},
	&Signature{Id: 82, Name: "rename", Args: []Arg{Arg{Name: "oldname", Type: type_stringc, Const: true}, Arg{Name: "newname", Type: type_stringc, Const: true}}},
	&Signature{Id: 83, Name: "mkdir", Args: []Arg{Arg{Name: "pathname", Type: type_stringc, Const: true}, Arg{Name: "mode", Type: type_int, Const: false}}},
	&Signature{Id: 84, Name: "rmdir", Args: []Arg{Arg{Name: "pathname", Type: type_stringc, Const: true}}},
	&Signature{Id: 85, Name: "creat", Args: []Arg{Arg{Name: "pathname", Type: type_stringc, Const: true}, Arg{Name: "mode", Type: type_int, Const: false}}},
	&Signature{Id: 86, Name: "link", Args: []Arg{Arg{Name: "oldname", Type: type_stringc, Const: true}, Arg{Name: "newname", Type: type_stringc, Const: true}}},
	&Signature{Id: 87, Name: "unlink", Args: []Arg{Arg{Name: "pathname", Type: type_stringc, Const: true}}},
	&Signature{Id: 88, Name: "symlink", Args: []Arg{Arg{Name: "oldname", Type: type_stringc, Const: true}, Arg{Name: "newname", Type: type_stringc, Const: true}}},
	&Signature{Id: 89, Name: "readlink", Args: []Arg{Arg{Name: "path", Type: type_stringc, Const: true}, Arg{Name: "buf", Type: type_stringc, Const: false}, Arg{Name: "bufsiz", Type: type_int, Const: false}}},
	&Signature{Id: 90, Name: "chmod", Args: []Arg{Arg{Name: "filename", Type: type_stringc, Const: true}, Arg{Name: "mode", Type: type_uint16, Const: false}}},
	&Signature{Id: 91, Name: "fchmod", Args: []Arg{Arg{Name: "fd", Type: type_uint32, Const: false}, Arg{Name: "mode", Type: type_uint16, Const: false}}},
	&Signature{Id: 92, Name: "chown", Args: []Arg{Arg{Name: "filename", Type: type_stringc, Const: true}, Arg{Name: "user", Type: type_uint32, Const: false}, Arg{Name: "group", Type: type_uint32, Const: false}}},
	&Signature{Id: 93, Name: "fchown", Args: []Arg{Arg{Name: "fd", Type: type_uint32, Const: false}, Arg{Name: "user", Type: type_uint32, Const: false}, Arg{Name: "group", Type: type_uint32, Const: false}}},
	&Signature{Id: 94, Name: "lchown", Args: []Arg{Arg{Name: "filename", Type: type_stringc, Const: true}, Arg{Name: "user", Type: type_uint32, Const: false}, Arg{Name: "group", Type: type_uint32, Const: false}}},
	&Signature{Id: 95, Name: "umask", Args: []Arg{Arg{Name: "mask", Type: type_int, Const: false}}},
	&Signature{Id: 96, Name: "gettimeofday", Args: []Arg{Arg{Name: "tv", Type: &type_unknownstruct, Const: false}, Arg{Name: "tz", Type: &type_unknownstruct, Const: false}}},
	&Signature{Id: 97, Name: "getrlimit", Args: []Arg{Arg{Name: "resource", Type: type_uint32, Const: false}, Arg{Name: "rlim", Type: &type_unknownstruct, Const: false}}},
	&Signature{Id: 98, Name: "getrusage", Args: []Arg{Arg{Name: "who", Type: type_int, Const: false}, Arg{Name: "ru", Type: &type_unknownstruct, Const: false}}},
	&Signature{Id: 99, Name: "sysinfo", Args: []Arg{Arg{Name: "info", Type: &type_unknownstruct, Const: false}}},
	&Signature{Id: 100, Name: "times", Args: []Arg{Arg{Name: "info", Type: &type_unknownstruct, Const: false}}},
	&Signature{Id: 101, Name: "ptrace", Args: []Arg{Arg{Name: "request", Type: type_int32, Const: false}, Arg{Name: "pid", Type: type_int32, Const: false}, Arg{Name: "addr", Type: type_uint64, Const: false}, Arg{Name: "data", Type: type_uint64, Const: false}}},
	&Signature{Id: 102, Name: "getuid", Args: []Arg{}},
	&Signature{Id: 103, Name: "syslog", Args: []Arg{Arg{Name: "type", Type: type_int, Const: false}, Arg{Name: "buf", Type: type_stringc, Const: false}, Arg{Name: "len", Type: type_int, Const: false}}},
	&Signature{Id: 104, Name: "getgid", Args: []Arg{}},
	&Signature{Id: 105, Name: "setuid", Args: []Arg{Arg{Name: "uid", Type: type_uint32, Const: false}}},
	&Signature{Id: 106, Name: "setgid", Args: []Arg{Arg{Name: "gid", Type: type_uint32, Const: false}}},
	&Signature{Id: 107, Name: "geteuid", Args: []Arg{}},
	&Signature{Id: 108, Name: "getegid", Args: []Arg{}},
	&Signature{Id: 109, Name: "setpgid", Args: []Arg{Arg{Name: "pid", Type: type_int32, Const: false}, Arg{Name: "pgid", Type: type_int32, Const: false}}},
	&Signature{Id: 110, Name: "getppid", Args: []Arg{}},
	&Signature{Id: 111, Name: "getpgrp", Args: []Arg{}},
	&Signature{Id: 112, Name: "setsid", Args: []Arg{}},
	&Signature{Id: 113, Name: "setreuid", Args: []Arg{Arg{Name: "ruid", Type: type_uint32, Const: false}, Arg{Name: "euid", Type: type_uint32, Const: false}}},
	&Signature{Id: 114, Name: "setregid", Args: []Arg{Arg{Name: "rgid", Type: type_uint32, Const: false}, Arg{Name: "egid", Type: type_uint32, Const: false}}},
	&Signature{Id: 115, Name: "getgroups", Args: []Arg{Arg{Name: "gidsetsize", Type: type_int, Const: false}, Arg{Name: "grouplist", Type: &type_uint32, Const: false}}},
	&Signature{Id: 116, Name: "setgroups", Args: []Arg{Arg{Name: "gidsetsize", Type: type_int, Const: false}, Arg{Name: "grouplist", Type: &type_uint32, Const: false}}},
	&Signature{Id: 117, Name: "setresuid", Args: []Arg{Arg{Name: "ruid", Type: &type_uint32, Const: false}, Arg{Name: "euid", Type: &type_uint32, Const: false}, Arg{Name: "suid", Type: &type_uint32, Const: false}}},
	&Signature{Id: 118, Name: "getresuid", Args: []Arg{Arg{Name: "ruid", Type: &type_uint32, Const: false}, Arg{Name: "euid", Type: &type_uint32, Const: false}, Arg{Name: "suid", Type: &type_uint32, Const: false}}},
	&Signature{Id: 119, Name: "setresgid", Args: []Arg{Arg{Name: "rgid", Type: type_uint32, Const: false}, Arg{Name: "egid", Type: type_uint32, Const: false}, Arg{Name: "sgid", Type: type_uint32, Const: false}}},
	&Signature{Id: 120, Name: "getresgid", Args: []Arg{Arg{Name: "rgid", Type: &type_uint32, Const: false}, Arg{Name: "egid", Type: &type_uint32, Const: false}, Arg{Name: "sgid", Type: &type_uint32, Const: false}}},
	&Signature{Id: 121, Name: "getpgid", Args: []Arg{Arg{Name: "pid", Type: type_int32, Const: false}}},
	&Signature{Id: 122, Name: "setfsuid", Args: []Arg{Arg{Name: "uid", Type: type_uint32, Const: false}}},
	&Signature{Id: 123, Name: "setfsgid", Args: []Arg{Arg{Name: "gid", Type: type_uint32, Const: false}}},
	&Signature{Id: 124, Name: "getsid", Args: []Arg{Arg{Name: "pid", Type: type_int32, Const: false}}},
	&Signature{Id: 125, Name: "capget", Args: []Arg{Arg{Name: "header", Type: type_unknownstruct, Const: false}, Arg{Name: "dataptr", Type: type_unknownstruct, Const: false}}},
	&Signature{Id: 126, Name: "capset", Args: []Arg{Arg{Name: "header", Type: type_unknownstruct, Const: false}, Arg{Name: "data", Type: type_unknownstruct, Const: true}}},
	&Signature{Id: 127, Name: "rt_sigpending", Args: []Arg{Arg{Name: "set", Type: &type_unknownstruct, Const: false}, Arg{Name: "sigsetsize", Type: type_uint64, Const: false}}},
	&Signature{Id: 128, Name: "rt_sigtimedwait", Args: []Arg{Arg{Name: "uthese", Type: &type_unknownstruct, Const: true}, Arg{Name: "uinfo", Type: &type_unknownstruct, Const: false}, Arg{Name: "uts", Type: &type_unknownstruct, Const: true}, Arg{Name: "sigsetsize", Type: type_uint64, Const: false}}},
	&Signature{Id: 129, Name: "rt_sigqueueinfo", Args: []Arg{Arg{Name: "pid", Type: type_int32, Const: false}, Arg{Name: "sig", Type: type_int, Const: false}, Arg{Name: "uinfo", Type: &type_unknownstruct, Const: false}}},
	&Signature{Id: 130, Name: "rt_sigsuspend", Args: []Arg{Arg{Name: "unewset", Type: &type_unknownstruct, Const: false}, Arg{Name: "sigsetsize", Type: type_uint64, Const: false}}},
	&Signature{Id: 131, Name: "sigaltstack", Args: []Arg{Arg{Name: "uss", Type: &type_unknownstruct, Const: true}, Arg{Name: "uoss", Type: &type_unknownstruct, Const: false}}},
	&Signature{Id: 132, Name: "utime", Args: []Arg{Arg{Name: "filename", Type: type_stringc, Const: false}, Arg{Name: "times", Type: &type_unknownstruct, Const: false}}},
	&Signature{Id: 133, Name: "mknod", Args: []Arg{Arg{Name: "filename", Type: type_stringc, Const: true}, Arg{Name: "mode", Type: type_int, Const: false}, Arg{Name: "dev", Type: type_uint32, Const: false}}},
	&Signature{Id: 134, Name: "uselib", Args: []Arg{Arg{Name: "library", Type: type_stringc, Const: true}}},
	&Signature{Id: 135, Name: "personality", Args: []Arg{Arg{Name: "personality", Type: type_uint32, Const: false}}},
	&Signature{Id: 136, Name: "ustat", Args: []Arg{Arg{Name: "dev", Type: type_uint32, Const: false}, Arg{Name: "ubuf", Type: &type_unknownstruct, Const: false}}},
	&Signature{Id: 137, Name: "statfs", Args: []Arg{Arg{Name: "pathname", Type: type_stringc, Const: true}, Arg{Name: "buf", Type: &type_unknownstruct, Const: false}}},
	&Signature{Id: 138, Name: "fstatfs", Args: []Arg{Arg{Name: "fd", Type: type_uint32, Const: false}, Arg{Name: "buf", Type: &type_unknownstruct, Const: false}}},
	&Signature{Id: 139, Name: "sysfs", Args: []Arg{Arg{Name: "option", Type: type_int, Const: false}, Arg{Name: "arg1", Type: type_uint64, Const: false}, Arg{Name: "arg2", Type: type_uint64, Const: false}}},
	&Signature{Id: 140, Name: "getpriority", Args: []Arg{Arg{Name: "which", Type: type_int, Const: false}, Arg{Name: "who", Type: type_int, Const: false}}},
	&Signature{Id: 141, Name: "setpriority", Args: []Arg{Arg{Name: "which", Type: type_int, Const: false}, Arg{Name: "who", Type: type_int, Const: false}, Arg{Name: "niceval", Type: type_int, Const: false}}},
	&Signature{Id: 142, Name: "sched_setparam", Args: []Arg{Arg{Name: "pid", Type: type_int32, Const: false}, Arg{Name: "param", Type: &type_unknownstruct, Const: false}}},
	&Signature{Id: 143, Name: "sched_getparam", Args: []Arg{Arg{Name: "pid", Type: type_int32, Const: false}, Arg{Name: "param", Type: &type_unknownstruct, Const: false}}},
	&Signature{Id: 144, Name: "sched_setscheduler", Args: []Arg{Arg{Name: "pid", Type: type_int32, Const: false}, Arg{Name: "policy", Type: type_int, Const: false}, Arg{Name: "param", Type: &type_unknownstruct, Const: false}}},
	&Signature{Id: 145, Name: "sched_getscheduler", Args: []Arg{Arg{Name: "pid", Type: type_int32, Const: false}}},
	&Signature{Id: 146, Name: "sched_get_priority_max", Args: []Arg{Arg{Name: "policy", Type: type_int, Const: false}}},
	&Signature{Id: 147, Name: "sched_get_priority_min", Args: []Arg{Arg{Name: "policy", Type: type_int, Const: false}}},
	&Signature{Id: 148, Name: "sched_rr_get_interval", Args: []Arg{Arg{Name: "pid", Type: type_int32, Const: false}, Arg{Name: "interval", Type: &type_unknownstruct, Const: false}}},
	&Signature{Id: 149, Name: "mlock", Args: []Arg{Arg{Name: "start", Type: type_uint64, Const: false}, Arg{Name: "len", Type: type_uint64, Const: false}}},
	&Signature{Id: 150, Name: "munlock", Args: []Arg{Arg{Name: "start", Type: type_uint64, Const: false}, Arg{Name: "len", Type: type_uint64, Const: false}}},
	&Signature{Id: 151, Name: "mlockall", Args: []Arg{Arg{Name: "flags", Type: type_int, Const: false}}},
	&Signature{Id: 152, Name: "munlockall", Args: []Arg{}},
	&Signature{Id: 153, Name: "vhangup", Args: []Arg{}},
	&Signature{Id: 154, Name: "modify_ldt", Args: []Arg{Arg{Name: "func", Type: type_int, Const: false}, Arg{Name: "ptr", Type: &type_uint8, Const: false}, Arg{Name: "bytecount", Type: type_uint64, Const: false}}},
	&Signature{Id: 155, Name: "pivot_root", Args: []Arg{Arg{Name: "new_root", Type: type_stringc, Const: true}, Arg{Name: "put_old", Type: type_stringc, Const: true}}},
	&Signature{Id: 156, Name: "_sysctl", Args: []Arg{Arg{Name: "args", Type: &type_unknownstruct, Const: false}}},
	&Signature{Id: 157, Name: "prctl", Args: []Arg{Arg{Name: "option", Type: type_int, Const: false}, Arg{Name: "arg2", Type: type_uint64, Const: false}, Arg{Name: "arg3", Type: type_uint64, Const: false}, Arg{Name: "arg4", Type: type_uint64, Const: false}, Arg{Name: "arg5", Type: type_uint64, Const: false}}},
	&Signature{Id: 158, Name: "arch_prctl", Args: []Arg{Arg{Name: "task", Type: &type_unknownstruct, Const: false}, Arg{Name: "code", Type: type_int, Const: false}, Arg{Name: "addr", Type: &type_uint64, Const: false}}},
	&Signature{Id: 159, Name: "adjtimex", Args: []Arg{Arg{Name: "txc_p", Type: &type_unknownstruct, Const: false}}},
	&Signature{Id: 160, Name: "setrlimit", Args: []Arg{Arg{Name: "resource", Type: type_uint32, Const: false}, Arg{Name: "rlim", Type: &type_unknownstruct, Const: false}}},
	&Signature{Id: 161, Name: "chroot", Args: []Arg{Arg{Name: "filename", Type: type_stringc, Const: true}}},
	&Signature{Id: 162, Name: "sync", Args: []Arg{}},
	&Signature{Id: 163, Name: "acct", Args: []Arg{Arg{Name: "name", Type: type_stringc, Const: true}}},
	&Signature{Id: 164, Name: "settimeofday", Args: []Arg{Arg{Name: "tv", Type: &type_unknownstruct, Const: false}, Arg{Name: "tz", Type: &type_unknownstruct, Const: false}}},
	&Signature{Id: 165, Name: "mount", Args: []Arg{Arg{Name: "dev_name", Type: type_stringc, Const: false}, Arg{Name: "dir_name", Type: type_stringc, Const: false}, Arg{Name: "type", Type: type_stringc, Const: false}, Arg{Name: "flags", Type: type_uint64, Const: false}, Arg{Name: "data", Type: &type_uint8, Const: false}}},
	&Signature{Id: 166, Name: "umount2", Args: []Arg{Arg{Name: "target", Type: type_stringc, Const: true}, Arg{Name: "flags", Type: type_int, Const: false}}},
	&Signature{Id: 167, Name: "swapon", Args: []Arg{Arg{Name: "specialfile", Type: type_stringc, Const: true}, Arg{Name: "swap_flags", Type: type_int, Const: false}}},
	&Signature{Id: 168, Name: "swapoff", Args: []Arg{Arg{Name: "specialfile", Type: type_stringc, Const: true}}},
	&Signature{Id: 169, Name: "reboot", Args: []Arg{Arg{Name: "magic1", Type: type_int, Const: false}, Arg{Name: "magic2", Type: type_int, Const: false}, Arg{Name: "cmd", Type: type_uint32, Const: false}, Arg{Name: "arg", Type: &type_uint8, Const: false}}},
	&Signature{Id: 170, Name: "sethostname", Args: []Arg{Arg{Name: "name", Type: type_stringc, Const: false}, Arg{Name: "len", Type: type_int, Const: false}}},
	&Signature{Id: 171, Name: "setdomainname", Args: []Arg{Arg{Name: "name", Type: type_stringc, Const: false}, Arg{Name: "len", Type: type_int, Const: false}}},
	&Signature{Id: 172, Name: "iopl", Args: []Arg{Arg{Name: "level", Type: type_uint32, Const: false}, Arg{Name: "regs", Type: &type_unknownstruct, Const: false}}},
	&Signature{Id: 173, Name: "ioperm", Args: []Arg{Arg{Name: "from", Type: type_uint64, Const: false}, Arg{Name: "num", Type: type_uint64, Const: false}, Arg{Name: "turn_on", Type: type_int, Const: false}}},
	&Signature{Id: 175, Name: "init_module", Args: []Arg{Arg{Name: "umod", Type: &type_uint8, Const: false}, Arg{Name: "len", Type: type_uint64, Const: false}, Arg{Name: "uargs", Type: type_stringc, Const: true}}},
	&Signature{Id: 176, Name: "delete_module", Args: []Arg{Arg{Name: "name_user", Type: type_stringc, Const: true}, Arg{Name: "flags", Type: type_uint32, Const: false}}},
	&unknownSignature, // 176
	&unknownSignature, // 177
	&Signature{Id: 179, Name: "quotactl", Args: []Arg{Arg{Name: "cmd", Type: type_uint32, Const: false}, Arg{Name: "special", Type: type_stringc, Const: true}, Arg{Name: "id", Type: type_uint32, Const: false}, Arg{Name: "addr", Type: &type_uint8, Const: false}}},
	&Signature{Id: 180, Name: "nfsservctl", Args: []Arg{Arg{Name: "cmd", Type: type_int, Const: false}, Arg{Name: "argp", Type: &type_unknownstruct, Const: false}, Arg{Name: "resp", Type: &type_unknownstruct, Const: false}}},
	&unknownSignature, // 180
	&unknownSignature, // 181
	&unknownSignature, // 182
	&unknownSignature, // 183
	&unknownSignature, // 184
	&Signature{Id: 186, Name: "gettid", Args: []Arg{}},
	&Signature{Id: 187, Name: "readahead", Args: []Arg{Arg{Name: "fd", Type: type_int, Const: false}, Arg{Name: "offset", Type: type_uint64, Const: false}, Arg{Name: "count", Type: type_uint64, Const: false}}},
	&Signature{Id: 188, Name: "setxattr", Args: []Arg{Arg{Name: "pathname", Type: type_stringc, Const: true}, Arg{Name: "name", Type: type_stringc, Const: true}, Arg{Name: "value", Type: &type_uint8, Const: true}, Arg{Name: "size", Type: type_uint64, Const: false}, Arg{Name: "flags", Type: type_int, Const: false}}},
	&Signature{Id: 189, Name: "lsetxattr", Args: []Arg{Arg{Name: "pathname", Type: type_stringc, Const: true}, Arg{Name: "name", Type: type_stringc, Const: true}, Arg{Name: "value", Type: &type_uint8, Const: true}, Arg{Name: "size", Type: type_uint64, Const: false}, Arg{Name: "flags", Type: type_int, Const: false}}},
	&Signature{Id: 190, Name: "fsetxattr", Args: []Arg{Arg{Name: "fd", Type: type_int, Const: false}, Arg{Name: "name", Type: type_stringc, Const: true}, Arg{Name: "value", Type: &type_uint8, Const: true}, Arg{Name: "size", Type: type_uint64, Const: false}, Arg{Name: "flags", Type: type_int, Const: false}}},
	&Signature{Id: 191, Name: "getxattr", Args: []Arg{Arg{Name: "pathname", Type: type_stringc, Const: true}, Arg{Name: "name", Type: type_stringc, Const: true}, Arg{Name: "value", Type: &type_uint8, Const: false}, Arg{Name: "size", Type: type_uint64, Const: false}}},
	&Signature{Id: 192, Name: "lgetxattr", Args: []Arg{Arg{Name: "pathname", Type: type_stringc, Const: true}, Arg{Name: "name", Type: type_stringc, Const: true}, Arg{Name: "value", Type: &type_uint8, Const: false}, Arg{Name: "size", Type: type_uint64, Const: false}}},
	&Signature{Id: 193, Name: "fgetxattr", Args: []Arg{Arg{Name: "fd", Type: type_int, Const: false}, Arg{Name: "name", Type: type_stringc, Const: true}, Arg{Name: "value", Type: &type_uint8, Const: false}, Arg{Name: "size", Type: type_uint64, Const: false}}},
	&Signature{Id: 194, Name: "listxattr", Args: []Arg{Arg{Name: "pathname", Type: type_stringc, Const: true}, Arg{Name: "list", Type: type_stringc, Const: false}, Arg{Name: "size", Type: type_uint64, Const: false}}},
	&Signature{Id: 195, Name: "llistxattr", Args: []Arg{Arg{Name: "pathname", Type: type_stringc, Const: true}, Arg{Name: "list", Type: type_stringc, Const: false}, Arg{Name: "size", Type: type_uint64, Const: false}}},
	&Signature{Id: 196, Name: "flistxattr", Args: []Arg{Arg{Name: "fd", Type: type_int, Const: false}, Arg{Name: "list", Type: type_stringc, Const: false}, Arg{Name: "size", Type: type_uint64, Const: false}}},
	&Signature{Id: 197, Name: "removexattr", Args: []Arg{Arg{Name: "pathname", Type: type_stringc, Const: true}, Arg{Name: "name", Type: type_stringc, Const: true}}},
	&Signature{Id: 198, Name: "lremovexattr", Args: []Arg{Arg{Name: "pathname", Type: type_stringc, Const: true}, Arg{Name: "name", Type: type_stringc, Const: true}}},
	&Signature{Id: 199, Name: "fremovexattr", Args: []Arg{Arg{Name: "fd", Type: type_int, Const: false}, Arg{Name: "name", Type: type_stringc, Const: true}}},
	&Signature{Id: 200, Name: "tkill", Args: []Arg{Arg{Name: "pid", Type: type_int32, Const: false}, Arg{Name: "sig", Type: type_int, Const: false}}},
	&Signature{Id: 201, Name: "time", Args: []Arg{Arg{Name: "tloc", Type: &type_uint32, Const: false}}},
	&Signature{Id: 202, Name: "futex", Args: []Arg{Arg{Name: "uaddr", Type: &type_uint32, Const: false}, Arg{Name: "op", Type: type_int, Const: false}, Arg{Name: "val", Type: type_uint32, Const: false}, Arg{Name: "utime", Type: &type_unknownstruct, Const: false}, Arg{Name: "uaddr2", Type: &type_uint32, Const: false}, Arg{Name: "val3", Type: type_uint32, Const: false}}},
	&Signature{Id: 203, Name: "sched_setaffinity", Args: []Arg{Arg{Name: "pid", Type: type_int32, Const: false}, Arg{Name: "len", Type: type_uint32, Const: false}, Arg{Name: "user_mask_ptr", Type: &type_uint64, Const: false}}},
	&Signature{Id: 204, Name: "sched_getaffinity", Args: []Arg{Arg{Name: "pid", Type: type_int32, Const: false}, Arg{Name: "len", Type: type_uint32, Const: false}, Arg{Name: "user_mask_ptr", Type: &type_uint64, Const: false}}},
	&Signature{Id: 205, Name: "set_thread_area", Args: []Arg{Arg{Name: "u_info", Type: &type_unknownstruct, Const: false}}},
	&Signature{Id: 206, Name: "io_setup", Args: []Arg{Arg{Name: "nr_events", Type: type_uint32, Const: false}, Arg{Name: "ctxp", Type: &type_uint32, Const: false}}},
	&Signature{Id: 207, Name: "io_destroy", Args: []Arg{Arg{Name: "ctx", Type: type_uint32, Const: false}}},
	&Signature{Id: 208, Name: "io_getevents", Args: []Arg{Arg{Name: "ctx_id", Type: type_uint32, Const: false}, Arg{Name: "min_nr", Type: type_int32, Const: false}, Arg{Name: "nr", Type: type_int32, Const: false}, Arg{Name: "events", Type: &type_unknownstruct, Const: false}}},
	&Signature{Id: 209, Name: "io_submit", Args: []Arg{Arg{Name: "ctx_id", Type: type_uint32, Const: false}, Arg{Name: "nr", Type: type_int32, Const: false}, Arg{Name: "iocbpp", Type: &type_unknownstruct, Const: false}}},
	&Signature{Id: 210, Name: "io_cancel", Args: []Arg{Arg{Name: "ctx_id", Type: type_uint32, Const: false}, Arg{Name: "iocb", Type: &type_unknownstruct, Const: false}, Arg{Name: "result", Type: &type_unknownstruct, Const: false}}},
	&unknownSignature, // 210
	&Signature{Id: 212, Name: "lookup_dcookie", Args: []Arg{Arg{Name: "cookie64", Type: type_uint64, Const: false}, Arg{Name: "buf", Type: type_int32, Const: false}, Arg{Name: "len", Type: type_int32, Const: false}}},
	&Signature{Id: 213, Name: "epoll_create", Args: []Arg{Arg{Name: "size", Type: type_int, Const: false}}},
	&unknownSignature, // 213
	&unknownSignature, // 214
	&Signature{Id: 216, Name: "remap_file_pages", Args: []Arg{Arg{Name: "start", Type: type_uint64, Const: false}, Arg{Name: "size", Type: type_uint64, Const: false}, Arg{Name: "prot", Type: type_uint64, Const: false}, Arg{Name: "pgoff", Type: type_uint64, Const: false}, Arg{Name: "flags", Type: type_uint64, Const: false}}},
	&Signature{Id: 217, Name: "getdents64", Args: []Arg{Arg{Name: "fd", Type: type_uint32, Const: false}, Arg{Name: "dirent", Type: &type_unknownstruct, Const: false}, Arg{Name: "count", Type: type_uint32, Const: false}}},
	&Signature{Id: 218, Name: "set_tid_address", Args: []Arg{Arg{Name: "tidptr", Type: &type_int, Const: false}}},
	&Signature{Id: 219, Name: "restart_syscall", Args: []Arg{}},
	&Signature{Id: 220, Name: "semtimedop", Args: []Arg{Arg{Name: "semid", Type: type_int, Const: false}, Arg{Name: "tsops", Type: &type_unknownstruct, Const: false}, Arg{Name: "nsops", Type: type_uint32, Const: false}, Arg{Name: "timeout", Type: &type_unknownstruct, Const: true}}},
	&Signature{Id: 221, Name: "fadvise64", Args: []Arg{Arg{Name: "fd", Type: type_int, Const: false}, Arg{Name: "offset", Type: type_uint64, Const: false}, Arg{Name: "len", Type: type_uint64, Const: false}, Arg{Name: "advice", Type: type_int, Const: false}}},
	&Signature{Id: 222, Name: "timer_create", Args: []Arg{Arg{Name: "which_clock", Type: type_uint32, Const: true}, Arg{Name: "timer_event_spec", Type: &type_unknownstruct, Const: false}, Arg{Name: "created_timer_id", Type: &type_int32, Const: false}}},
	&Signature{Id: 223, Name: "timer_settime", Args: []Arg{Arg{Name: "timer_id", Type: type_int32, Const: false}, Arg{Name: "flags", Type: type_int, Const: false}, Arg{Name: "new_setting", Type: &type_unknownstruct, Const: true}, Arg{Name: "old_setting", Type: &type_unknownstruct, Const: false}}},
	&Signature{Id: 224, Name: "timer_gettime", Args: []Arg{Arg{Name: "timer_id", Type: type_int32, Const: false}, Arg{Name: "setting", Type: &type_unknownstruct, Const: false}}},
	&Signature{Id: 225, Name: "timer_getoverrun", Args: []Arg{Arg{Name: "timer_id", Type: type_int32, Const: false}}},
	&Signature{Id: 226, Name: "timer_delete", Args: []Arg{Arg{Name: "timer_id", Type: type_int32, Const: false}}},
	&Signature{Id: 227, Name: "clock_settime", Args: []Arg{Arg{Name: "which_clock", Type: type_uint32, Const: true}, Arg{Name: "tp", Type: &type_unknownstruct, Const: true}}},
	&Signature{Id: 228, Name: "clock_gettime", Args: []Arg{Arg{Name: "which_clock", Type: type_uint32, Const: true}, Arg{Name: "tp", Type: &type_unknownstruct, Const: false}}},
	&Signature{Id: 229, Name: "clock_getres", Args: []Arg{Arg{Name: "which_clock", Type: type_uint32, Const: true}, Arg{Name: "tp", Type: &type_unknownstruct, Const: false}}},
	&Signature{Id: 230, Name: "clock_nanosleep", Args: []Arg{Arg{Name: "which_clock", Type: type_uint32, Const: true}, Arg{Name: "flags", Type: type_int, Const: false}, Arg{Name: "rqtp", Type: &type_unknownstruct, Const: true}, Arg{Name: "rmtp", Type: &type_unknownstruct, Const: false}}},
	&Signature{Id: 231, Name: "exit_group", Args: []Arg{Arg{Name: "error_code", Type: type_int, Const: false}}},
	&Signature{Id: 232, Name: "epoll_wait", Args: []Arg{Arg{Name: "epfd", Type: type_int, Const: false}, Arg{Name: "events", Type: &type_unknownstruct, Const: false}, Arg{Name: "maxevents", Type: type_int, Const: false}, Arg{Name: "timeout", Type: type_int, Const: false}}},
	&Signature{Id: 233, Name: "epoll_ctl", Args: []Arg{Arg{Name: "epfd", Type: type_int, Const: false}, Arg{Name: "op", Type: type_int, Const: false}, Arg{Name: "fd", Type: type_int, Const: false}, Arg{Name: "event", Type: &type_unknownstruct, Const: false}}},
	&Signature{Id: 234, Name: "tgkill", Args: []Arg{Arg{Name: "tgid", Type: type_int32, Const: false}, Arg{Name: "pid", Type: type_int32, Const: false}, Arg{Name: "sig", Type: type_int, Const: false}}},
	&Signature{Id: 235, Name: "utimes", Args: []Arg{Arg{Name: "filename", Type: type_stringc, Const: false}, Arg{Name: "utimes", Type: &type_unknownstruct, Const: false}}},
	&unknownSignature, // 235
	&Signature{Id: 237, Name: "mbind", Args: []Arg{Arg{Name: "start", Type: type_uint64, Const: false}, Arg{Name: "len", Type: type_uint64, Const: false}, Arg{Name: "mode", Type: type_uint64, Const: false}, Arg{Name: "nmask", Type: &type_uint64, Const: false}, Arg{Name: "maxnode", Type: type_uint64, Const: false}, Arg{Name: "flags", Type: type_uint64, Const: false}}},
	&Signature{Id: 238, Name: "set_mempolicy", Args: []Arg{Arg{Name: "mode", Type: type_int, Const: false}, Arg{Name: "nmask", Type: &type_uint64, Const: false}, Arg{Name: "maxnode", Type: type_uint64, Const: false}}},
	&Signature{Id: 239, Name: "get_mempolicy", Args: []Arg{Arg{Name: "policy", Type: &type_int, Const: false}, Arg{Name: "nmask", Type: &type_uint64, Const: false}, Arg{Name: "maxnode", Type: type_uint64, Const: false}, Arg{Name: "addr", Type: type_uint64, Const: false}, Arg{Name: "flags", Type: type_uint64, Const: false}}},
	&Signature{Id: 240, Name: "mq_open", Args: []Arg{Arg{Name: "u_name", Type: type_stringc, Const: true}, Arg{Name: "oflag", Type: type_int, Const: false}, Arg{Name: "mode", Type: type_uint16, Const: false}, Arg{Name: "u_attr", Type: &type_unknownstruct, Const: false}}},
	&Signature{Id: 241, Name: "mq_unlink", Args: []Arg{Arg{Name: "u_name", Type: type_stringc, Const: true}}},
	&Signature{Id: 242, Name: "mq_timedsend", Args: []Arg{Arg{Name: "mqdes", Type: type_int32, Const: false}, Arg{Name: "u_msg_ptr", Type: type_stringc, Const: true}, Arg{Name: "msg_len", Type: type_uint64, Const: false}, Arg{Name: "msg_prio", Type: type_uint32, Const: false}, Arg{Name: "u_abs_timeout", Type: &type_unknownstruct, Const: true}}},
	&Signature{Id: 243, Name: "mq_timedreceive", Args: []Arg{Arg{Name: "mqdes", Type: type_int32, Const: false}, Arg{Name: "u_msg_ptr", Type: type_stringc, Const: false}, Arg{Name: "msg_len", Type: type_uint64, Const: false}, Arg{Name: "u_msg_prio", Type: &type_uint32, Const: false}, Arg{Name: "u_abs_timeout", Type: &type_unknownstruct, Const: true}}},
	&Signature{Id: 244, Name: "mq_notify", Args: []Arg{Arg{Name: "mqdes", Type: type_int32, Const: false}, Arg{Name: "u_notification", Type: &type_unknownstruct, Const: true}}},
	&Signature{Id: 245, Name: "mq_getsetattr", Args: []Arg{Arg{Name: "mqdes", Type: type_int32, Const: false}, Arg{Name: "u_mqstat", Type: &type_unknownstruct, Const: true}, Arg{Name: "u_omqstat", Type: &type_unknownstruct, Const: false}}},
	&Signature{Id: 246, Name: "kexec_load", Args: []Arg{Arg{Name: "entry", Type: type_uint64, Const: false}, Arg{Name: "nr_segments", Type: type_uint64, Const: false}, Arg{Name: "segments", Type: &type_unknownstruct, Const: false}, Arg{Name: "flags", Type: type_uint64, Const: false}}},
	&Signature{Id: 247, Name: "waitid", Args: []Arg{Arg{Name: "which", Type: type_int, Const: false}, Arg{Name: "upid", Type: type_int32, Const: false}, Arg{Name: "infop", Type: &type_unknownstruct, Const: false}, Arg{Name: "options", Type: type_int, Const: false}, Arg{Name: "ru", Type: &type_unknownstruct, Const: false}}},
	&Signature{Id: 248, Name: "add_key", Args: []Arg{Arg{Name: "_type", Type: type_stringc, Const: true}, Arg{Name: "_description", Type: type_stringc, Const: true}, Arg{Name: "_payload", Type: &type_uint8, Const: true}, Arg{Name: "plen", Type: type_uint64, Const: false}}},
	&Signature{Id: 249, Name: "request_key", Args: []Arg{Arg{Name: "_type", Type: type_stringc, Const: true}, Arg{Name: "_description", Type: type_stringc, Const: true}, Arg{Name: "_callout_info", Type: type_stringc, Const: true}, Arg{Name: "destringid", Type: type_int32, Const: false}}},
	&Signature{Id: 250, Name: "keyctl", Args: []Arg{Arg{Name: "option", Type: type_int, Const: false}, Arg{Name: "arg2", Type: type_uint64, Const: false}, Arg{Name: "arg3", Type: type_uint64, Const: false}, Arg{Name: "arg4", Type: type_uint64, Const: false}, Arg{Name: "arg5", Type: type_uint64, Const: false}}},
	&Signature{Id: 251, Name: "ioprio_set", Args: []Arg{Arg{Name: "which", Type: type_int, Const: false}, Arg{Name: "who", Type: type_int, Const: false}, Arg{Name: "ioprio", Type: type_int, Const: false}}},
	&Signature{Id: 252, Name: "ioprio_get", Args: []Arg{Arg{Name: "which", Type: type_int, Const: false}, Arg{Name: "who", Type: type_int, Const: false}}},
	&Signature{Id: 253, Name: "inotify_init", Args: []Arg{}},
	&Signature{Id: 254, Name: "inotify_add_watch", Args: []Arg{Arg{Name: "fd", Type: type_int, Const: false}, Arg{Name: "pathname", Type: type_stringc, Const: true}, Arg{Name: "mask", Type: type_uint32, Const: false}}},
	&Signature{Id: 255, Name: "inotify_rm_watch", Args: []Arg{Arg{Name: "fd", Type: type_int, Const: false}, Arg{Name: "wd", Type: type_int32, Const: false}}},
	&Signature{Id: 256, Name: "migrate_pages", Args: []Arg{Arg{Name: "pid", Type: type_int32, Const: false}, Arg{Name: "maxnode", Type: type_uint64, Const: false}, Arg{Name: "old_nodes", Type: &type_uint64, Const: true}, Arg{Name: "new_nodes", Type: &type_uint64, Const: true}}},
	&Signature{Id: 257, Name: "openat", Args: []Arg{Arg{Name: "dfd", Type: type_int, Const: false}, Arg{Name: "filename", Type: type_stringc, Const: true}, Arg{Name: "flags", Type: type_int, Const: false}, Arg{Name: "mode", Type: type_int, Const: false}}},
	&Signature{Id: 258, Name: "mkdirat", Args: []Arg{Arg{Name: "dfd", Type: type_int, Const: false}, Arg{Name: "pathname", Type: type_stringc, Const: true}, Arg{Name: "mode", Type: type_int, Const: false}}},
	&Signature{Id: 259, Name: "mknodat", Args: []Arg{Arg{Name: "dfd", Type: type_int, Const: false}, Arg{Name: "filename", Type: type_stringc, Const: true}, Arg{Name: "mode", Type: type_int, Const: false}, Arg{Name: "dev", Type: type_uint32, Const: false}}},
	&Signature{Id: 260, Name: "fchownat", Args: []Arg{Arg{Name: "dfd", Type: type_int, Const: false}, Arg{Name: "filename", Type: type_stringc, Const: true}, Arg{Name: "user", Type: type_uint32, Const: false}, Arg{Name: "group", Type: type_uint32, Const: false}, Arg{Name: "flag", Type: type_int, Const: false}}},
	&Signature{Id: 261, Name: "futimesat", Args: []Arg{Arg{Name: "dfd", Type: type_int, Const: false}, Arg{Name: "filename", Type: type_stringc, Const: true}, Arg{Name: "utimes", Type: &type_unknownstruct, Const: false}}},
	&Signature{Id: 262, Name: "newfstatat", Args: []Arg{Arg{Name: "dfd", Type: type_int, Const: false}, Arg{Name: "filename", Type: type_stringc, Const: true}, Arg{Name: "statbuf", Type: &type_unknownstruct, Const: false}, Arg{Name: "flag", Type: type_int, Const: false}}},
	&Signature{Id: 263, Name: "unlinkat", Args: []Arg{Arg{Name: "dfd", Type: type_int, Const: false}, Arg{Name: "pathname", Type: type_stringc, Const: true}, Arg{Name: "flag", Type: type_int, Const: false}}},
	&Signature{Id: 264, Name: "renameat", Args: []Arg{Arg{Name: "oldfd", Type: type_int, Const: false}, Arg{Name: "oldname", Type: type_stringc, Const: true}, Arg{Name: "newfd", Type: type_int, Const: false}, Arg{Name: "newname", Type: type_stringc, Const: true}}},
	&Signature{Id: 265, Name: "linkat", Args: []Arg{Arg{Name: "oldfd", Type: type_int, Const: false}, Arg{Name: "oldname", Type: type_stringc, Const: true}, Arg{Name: "newfd", Type: type_int, Const: false}, Arg{Name: "newname", Type: type_stringc, Const: true}, Arg{Name: "flags", Type: type_int, Const: false}}},
	&Signature{Id: 266, Name: "symlinkat", Args: []Arg{Arg{Name: "oldname", Type: type_stringc, Const: true}, Arg{Name: "newfd", Type: type_int, Const: false}, Arg{Name: "newname", Type: type_stringc, Const: true}}},
	&Signature{Id: 267, Name: "readlinkat", Args: []Arg{Arg{Name: "dfd", Type: type_int, Const: false}, Arg{Name: "pathname", Type: type_stringc, Const: true}, Arg{Name: "buf", Type: type_stringc, Const: false}, Arg{Name: "bufsiz", Type: type_int, Const: false}}},
	&Signature{Id: 268, Name: "fchmodat", Args: []Arg{Arg{Name: "dfd", Type: type_int, Const: false}, Arg{Name: "filename", Type: type_stringc, Const: true}, Arg{Name: "mode", Type: type_uint16, Const: false}}},
	&Signature{Id: 269, Name: "faccessat", Args: []Arg{Arg{Name: "dfd", Type: type_int, Const: false}, Arg{Name: "filename", Type: type_stringc, Const: true}, Arg{Name: "mode", Type: type_int, Const: false}}},
	&Signature{Id: 270, Name: "pselect6", Args: []Arg{Arg{Name: "n", Type: type_int, Const: false}, Arg{Name: "inp", Type: &type_unknownstruct, Const: false}, Arg{Name: "outp", Type: &type_unknownstruct, Const: false}, Arg{Name: "exp", Type: &type_unknownstruct, Const: false}, Arg{Name: "tsp", Type: &type_unknownstruct, Const: false}, Arg{Name: "sig", Type: &type_uint8, Const: false}}},
	&Signature{Id: 271, Name: "ppoll", Args: []Arg{Arg{Name: "ufds", Type: &type_unknownstruct, Const: false}, Arg{Name: "nfds", Type: type_uint32, Const: false}, Arg{Name: "tsp", Type: &type_unknownstruct, Const: false}, Arg{Name: "sigmask", Type: &type_unknownstruct, Const: true}, Arg{Name: "sigsetsize", Type: type_uint64, Const: false}}},
	&Signature{Id: 272, Name: "unshare", Args: []Arg{Arg{Name: "unshare_flags", Type: type_uint64, Const: false}}},
	&Signature{Id: 273, Name: "set_robust_list", Args: []Arg{Arg{Name: "head", Type: &type_unknownstruct, Const: false}, Arg{Name: "len", Type: type_uint64, Const: false}}},
	&Signature{Id: 274, Name: "get_robust_list", Args: []Arg{Arg{Name: "pid", Type: type_int, Const: false}, Arg{Name: "head_ptr", Type: &type_unknownstruct, Const: false}, Arg{Name: "len_ptr", Type: &type_uint64, Const: false}}},
	&Signature{Id: 275, Name: "splice", Args: []Arg{Arg{Name: "fd_in", Type: type_int, Const: false}, Arg{Name: "off_in", Type: &type_uint64, Const: false}, Arg{Name: "fd_out", Type: type_int, Const: false}, Arg{Name: "off_out", Type: &type_uint64, Const: false}, Arg{Name: "len", Type: type_uint64, Const: false}, Arg{Name: "flags", Type: type_uint32, Const: false}}},
	&Signature{Id: 276, Name: "tee", Args: []Arg{Arg{Name: "fdin", Type: type_int, Const: false}, Arg{Name: "fdout", Type: type_int, Const: false}, Arg{Name: "len", Type: type_uint64, Const: false}, Arg{Name: "flags", Type: type_uint32, Const: false}}},
	&Signature{Id: 277, Name: "sync_file_range", Args: []Arg{Arg{Name: "fd", Type: type_int32, Const: false}, Arg{Name: "offset", Type: type_uint64, Const: false}, Arg{Name: "bytes", Type: type_uint64, Const: false}, Arg{Name: "flags", Type: type_int32, Const: false}}},
	&Signature{Id: 278, Name: "vmsplice", Args: []Arg{Arg{Name: "fd", Type: type_int, Const: false}, Arg{Name: "iov", Type: &type_unknownstruct, Const: true}, Arg{Name: "nr_segs", Type: type_uint64, Const: false}, Arg{Name: "flags", Type: type_uint32, Const: false}}},
	&Signature{Id: 279, Name: "move_pages", Args: []Arg{Arg{Name: "pid", Type: type_int32, Const: false}, Arg{Name: "nr_pages", Type: type_uint64, Const: false}, Arg{Name: "pages", Type: &type_uintptr, Const: true}, Arg{Name: "nodes", Type: &type_int, Const: true}, Arg{Name: "status", Type: &type_int, Const: false}, Arg{Name: "flags", Type: type_int, Const: false}}},
	&Signature{Id: 280, Name: "utimensat", Args: []Arg{Arg{Name: "dfd", Type: type_int, Const: false}, Arg{Name: "filename", Type: type_stringc, Const: true}, Arg{Name: "utimes", Type: &type_unknownstruct, Const: false}, Arg{Name: "flags", Type: type_int, Const: false}}},
	&Signature{Id: 281, Name: "epoll_pwait", Args: []Arg{Arg{Name: "epfd", Type: type_int, Const: false}, Arg{Name: "events", Type: &type_unknownstruct, Const: false}, Arg{Name: "maxevents", Type: type_int, Const: false}, Arg{Name: "timeout", Type: type_int, Const: false}, Arg{Name: "sigmask", Type: &type_unknownstruct, Const: true}, Arg{Name: "sigsetsize", Type: type_uint64, Const: false}}},
	&Signature{Id: 282, Name: "signalfd", Args: []Arg{Arg{Name: "ufd", Type: type_int, Const: false}, Arg{Name: "user_mask", Type: &type_unknownstruct, Const: false}, Arg{Name: "sizemask", Type: type_uint64, Const: false}}},
	&Signature{Id: 283, Name: "timerfd_create", Args: []Arg{Arg{Name: "clockid", Type: type_int, Const: false}, Arg{Name: "flags", Type: type_int, Const: false}}},
	&Signature{Id: 284, Name: "eventfd", Args: []Arg{Arg{Name: "count", Type: type_uint32, Const: false}}},
	&Signature{Id: 285, Name: "fallocate", Args: []Arg{Arg{Name: "fd", Type: type_int32, Const: false}, Arg{Name: "mode", Type: type_int32, Const: false}, Arg{Name: "offset", Type: type_uint64, Const: false}, Arg{Name: "len", Type: type_uint64, Const: false}}},
	&Signature{Id: 286, Name: "timerfd_settime", Args: []Arg{Arg{Name: "ufd", Type: type_int, Const: false}, Arg{Name: "flags", Type: type_int, Const: false}, Arg{Name: "utmr", Type: &type_unknownstruct, Const: true}, Arg{Name: "otmr", Type: &type_unknownstruct, Const: false}}},
	&Signature{Id: 287, Name: "timerfd_gettime", Args: []Arg{Arg{Name: "ufd", Type: type_int, Const: false}, Arg{Name: "otmr", Type: &type_unknownstruct, Const: false}}},
	&Signature{Id: 288, Name: "accept4", Args: []Arg{Arg{Name: "fd", Type: type_int, Const: false}, Arg{Name: "upeer_sockaddr", Type: &type_unknownstruct, Const: false}, Arg{Name: "upeer_addrlen", Type: &type_int, Const: false}, Arg{Name: "flags", Type: type_int, Const: false}}},
	&Signature{Id: 289, Name: "signalfd4", Args: []Arg{Arg{Name: "ufd", Type: type_int, Const: false}, Arg{Name: "user_mask", Type: &type_unknownstruct, Const: false}, Arg{Name: "sizemask", Type: type_uint64, Const: false}, Arg{Name: "flags", Type: type_int, Const: false}}},
	&Signature{Id: 290, Name: "eventfd2", Args: []Arg{Arg{Name: "count", Type: type_uint32, Const: false}, Arg{Name: "flags", Type: type_int, Const: false}}},
	&Signature{Id: 291, Name: "epoll_create1", Args: []Arg{Arg{Name: "flags", Type: type_int, Const: false}}},
	&Signature{Id: 292, Name: "dup3", Args: []Arg{Arg{Name: "oldfd", Type: type_uint32, Const: false}, Arg{Name: "newfd", Type: type_uint32, Const: false}, Arg{Name: "flags", Type: type_int, Const: false}}},
	&Signature{Id: 293, Name: "pipe2", Args: []Arg{Arg{Name: "filedes", Type: &type_int, Const: false}, Arg{Name: "flags", Type: type_int, Const: false}}},
	&Signature{Id: 294, Name: "inotify_init1", Args: []Arg{Arg{Name: "flags", Type: type_int, Const: false}}},
	&Signature{Id: 295, Name: "preadv", Args: []Arg{Arg{Name: "fd", Type: type_uint64, Const: false}, Arg{Name: "vec", Type: &type_unknownstruct, Const: true}, Arg{Name: "vlen", Type: type_uint64, Const: false}, Arg{Name: "pos_l", Type: type_uint64, Const: false}, Arg{Name: "pos_h", Type: type_uint64, Const: false}}},
	&Signature{Id: 296, Name: "pwritev", Args: []Arg{Arg{Name: "fd", Type: type_uint64, Const: false}, Arg{Name: "vec", Type: &type_unknownstruct, Const: true}, Arg{Name: "vlen", Type: type_uint64, Const: false}, Arg{Name: "pos_l", Type: type_uint64, Const: false}, Arg{Name: "pos_h", Type: type_uint64, Const: false}}},
	&Signature{Id: 297, Name: "rt_tgsigqueueinfo", Args: []Arg{Arg{Name: "tgid", Type: type_int32, Const: false}, Arg{Name: "pid", Type: type_int32, Const: false}, Arg{Name: "sig", Type: type_int, Const: false}, Arg{Name: "uinfo", Type: &type_unknownstruct, Const: false}}},
	&Signature{Id: 298, Name: "perf_event_open", Args: []Arg{Arg{Name: "attr_uptr", Type: &type_unknownstruct, Const: false}, Arg{Name: "pid", Type: type_int32, Const: false}, Arg{Name: "cpu", Type: type_int, Const: false}, Arg{Name: "group_fd", Type: type_int, Const: false}, Arg{Name: "flags", Type: type_uint64, Const: false}}},
	&Signature{Id: 299, Name: "recvmmsg", Args: []Arg{Arg{Name: "fd", Type: type_int, Const: false}, Arg{Name: "mmsg", Type: &type_unknownstruct, Const: false}, Arg{Name: "vlen", Type: type_uint32, Const: false}, Arg{Name: "flags", Type: type_uint32, Const: false}, Arg{Name: "timeout", Type: &type_unknownstruct, Const: false}}},
	&Signature{Id: 300, Name: "fanotify_init", Args: []Arg{Arg{Name: "flags", Type: type_uint32, Const: false}, Arg{Name: "event_f_flags", Type: type_uint32, Const: false}}},
	&Signature{Id: 301, Name: "fanotify_mark", Args: []Arg{Arg{Name: "fanotify_fd", Type: type_int32, Const: false}, Arg{Name: "flags", Type: type_int32, Const: false}, Arg{Name: "mask", Type: type_uint64, Const: false}, Arg{Name: "dfd", Type: type_int32, Const: false}, Arg{Name: "pathname", Type: type_int32, Const: false}}},
	&Signature{Id: 302, Name: "prlimit64", Args: []Arg{Arg{Name: "pid", Type: type_int32, Const: false}, Arg{Name: "resource", Type: type_uint32, Const: false}, Arg{Name: "new_rlim", Type: &type_unknownstruct, Const: true}, Arg{Name: "old_rlim", Type: &type_unknownstruct, Const: false}}},
	&Signature{Id: 303, Name: "name_to_handle_at", Args: []Arg{Arg{Name: "dfd", Type: type_int, Const: false}, Arg{Name: "name", Type: type_stringc, Const: true}, Arg{Name: "handle", Type: &type_unknownstruct, Const: false}, Arg{Name: "mnt_id", Type: &type_int, Const: false}, Arg{Name: "flag", Type: type_int, Const: false}}},
	&Signature{Id: 304, Name: "open_by_handle_at", Args: []Arg{Arg{Name: "dfd", Type: type_int, Const: false}, Arg{Name: "name", Type: type_stringc, Const: true}, Arg{Name: "handle", Type: &type_unknownstruct, Const: false}, Arg{Name: "mnt_id", Type: &type_int, Const: false}, Arg{Name: "flags", Type: type_int, Const: false}}},
	&Signature{Id: 305, Name: "clock_adjtime", Args: []Arg{Arg{Name: "which_clock", Type: type_uint32, Const: false}, Arg{Name: "tx", Type: &type_unknownstruct, Const: false}}},
	&Signature{Id: 306, Name: "syncfs", Args: []Arg{Arg{Name: "fd", Type: type_int, Const: false}}},
	&Signature{Id: 307, Name: "sendmmsg", Args: []Arg{Arg{Name: "fd", Type: type_int, Const: false}, Arg{Name: "mmsg", Type: &type_unknownstruct, Const: false}, Arg{Name: "vlen", Type: type_uint32, Const: false}, Arg{Name: "flags", Type: type_uint32, Const: false}}},
	&Signature{Id: 308, Name: "setns", Args: []Arg{Arg{Name: "fd", Type: type_int, Const: false}, Arg{Name: "nstype", Type: type_int, Const: false}}},
	&Signature{Id: 309, Name: "getcpu", Args: []Arg{Arg{Name: "cpup", Type: &type_uint32, Const: false}, Arg{Name: "nodep", Type: &type_uint32, Const: false}, Arg{Name: "unused", Type: &type_unknownstruct, Const: false}}},
	&Signature{Id: 310, Name: "process_vm_readv", Args: []Arg{Arg{Name: "pid", Type: type_int32, Const: false}, Arg{Name: "lvec", Type: &type_unknownstruct, Const: true}, Arg{Name: "liovcnt", Type: type_uint64, Const: false}, Arg{Name: "rvec", Type: &type_unknownstruct, Const: true}, Arg{Name: "riovcnt", Type: type_uint64, Const: false}, Arg{Name: "flags", Type: type_uint64, Const: false}}},
	&Signature{Id: 311, Name: "process_vm_writev", Args: []Arg{Arg{Name: "pid", Type: type_int32, Const: false}, Arg{Name: "lvec", Type: &type_unknownstruct, Const: true}, Arg{Name: "liovcnt", Type: type_uint64, Const: false}, Arg{Name: "rvec", Type: &type_unknownstruct, Const: true}, Arg{Name: "riovcnt", Type: type_uint64, Const: false}, Arg{Name: "flags", Type: type_uint64, Const: false}}},
}
