package types

var Types = map[string]string{
	"int":             "type_int",
	"unsigned int":    "type_uint32",
	"char":            "type_int8",
	"unsigned char":   "type_uint8",
	"size_t":          "type_uint64",
	"char *":          `type_stringc`,
	"unsigned char *": `type_buffer`,
	"long":            "type_int32",
	"unsigned long":   "type_uint64",
	"off_t":           "type_uint32",
	"loff_t":          "type_uint64",
	"key_t":           "type_int32",
	"pid_t":           "type_int32",
	"mode_t":          "type_uint16",
	"uid_t":           "type_uint32",
	"gid_t":           "type_uint32",
	"dev_t":           "type_uint32",
	"qid_t":           "type_uint32",
	"time_t":          "type_uint32",
	"clockid_t":       "type_uint32",
	"timer_t":         "type_int32",
	"mqd_t":           "type_int32",
	"key_serial_t":    "type_int32",
	"aio_context_t":   "type_uint32",
	"void":            "type_uint8",
	"u32":             "type_uint32",
	"u64":             "type_uint64",
	"__s32":           "type_int32",
	"__u64":           "type_uint64",
	"void *":          `type_uintptr`,

	"sigset_t":          "type_unknownstruct",
	"fd_set":            "type_unknownstruct",
	"cap_user_header_t": "type_unknownstruct",
	"cap_user_data_t":   "type_unknownstruct",
	"siginfo_t":         "type_unknownstruct",
	"stack_t":           "type_unknownstruct",
}
